Wrap from_raw_part
Cherry-picked from https://github.com/arthurprs/rust-rocksdb/pull/1

Note (Dave Rigby): This issue is fixed upstream in rust-rocksdb from v0.9.0 upwards via https://github.com/rust-rocksdb/rust-rocksdb/commit/d31e2bb88e08b0dfcf85252113c098b93821ec6c

It was found after upgrading from 1.76 to 1.81 that slice::from_raw_parts may be called with null pointer or len equal 0, causing panic. This commit fixes it.

```
panicked at library/core/src/panicking.rs:221:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5
   3: core::panicking::panic_nounwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:68:21
   5: core::slice::raw::from_raw_parts
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:75:17
   6: rocksdb::merge_operator::full_merge_callback
             at /home/runner/.cargo/git/checkouts/rust-rocksdb-c9431d8656f4ae9b/5d72760/src/merge_operator.rs:55:25
   7: _ZNK24crocksdb_mergeoperator_t11FullMergeV2ERKN7rocksdb13MergeOperator19MergeOperationInputEPNS1_20MergeOperationOutputE
             at /home/runner/.cargo/git/checkouts/rust-rocksdb-c9431d8656f4ae9b/5d72760/librocksdb_sys/crocksdb/c.cc:603:41
   8: _ZN7rocksdb11MergeHelper14TimedFullMergeEPKNS_13MergeOperatorERKNS_5SliceEPS5_RKSt6vectorIS4_SaIS4_EEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6LoggerEPNS_10StatisticsEPNS_11SystemClockEPS4_b
             at /home/runner/.cargo/git/checkouts/rust-rocksdb-c9431d8656f4ae9b/5d72760/librocksdb_sys/rocksdb/db/merge_helper.cc:88:42
```

This commit fixes it by wrapping slice::from_raw_parts call